# Site settings
title: Mark Monteno's Software Developer Portfolio
description: Mark Monteno's Software Developer Portfolio
keywords: Software, Software Developer, Developer, Development, Programming, 3D Graphics, 3D, Graphics, Portfolio

# User settings
username: Mark Monteno
user_description: Description of Core Skills
user_title: Software Developer
email: markmonteno@gmail.com
twitter_username: lorem_ipsum
github_username:  monteno-m
gplus_username:  lorem_ipsum

# Colors
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,299,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
