# Site settings
title: Mark Monteno's Software Developer Portfolio
description: Mark Monteno's Software Developer Portfolio
keywords: Software, Software Developer, Developer, Development, Programming, 3D Graphics, 3D, Graphics, Portfolio



# User settings
username: Mark Monteno
user_description: Description of Core Skills
user_title: Software Developer
email: markmonteno@gmail.com
twitter_username: lorem_ipsum
github_username:  monteno-m
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
